apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nossagrana-dev-api
  namespace: nossagrana-dev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: dev-api.nossagrana.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nossagrana-dev-api
                port:
                  number: 80
