apiVersion: apps/v1
kind: Deployment
metadata:
  name: nossagrana-api
  namespace: nossagrana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nossagrana-api
  template:
    metadata:
      labels:
        app: nossagrana-api
    spec:
      containers:
        - name: nossagrana-api
          image: ghcr.io/leoferolive/nossagrana-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: nossagrana-api-secrets
            - configMapRef:
                name: nossagrana-api-config
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 15

