apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nossagrana-web
  namespace: nossagrana
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: app.nossagrana.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nossagrana-web
                port:
                  number: 80
